name: Aluraflix API

on:
  push:
    branches: ['ci-app']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: 'ubuntu:latest'
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Check out app code
        uses: actions/checkout@v3
        with:
          path: app 
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Run tests
        run: | 
          python manage.py test
