name: Build application

on:
  push:
    branches: ['ci-app']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        os: ['ubuntu-latest']
    steps:
      - name: Check out app code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Set up database
        run: |
          python app/manage.py makemigrations
          python app/manage.py migrate
  
      - name: Load data to database
        run: |
          python app/manage.py loaddata app/aluraflix/fixtures/programas_iniciais.json

      - name: Run tests
        run: |
          python app/manage.py test

  build:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: ['ubuntu:latest']
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version}}

      - name: Run tests
        run: |
          python app/manage.py test
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r app/requirements.txt

      # - name: Set up database
      #   run: |
      #     python app/manage.py makemigrations
      #     python app/manage.py migrate

      # - name: Load data to database
      #   run: |
      #     python app/manage.py loaddata app/aluraflix/fixtures/programas_iniciais.json
