name: Deploy Aluraflix API

on:
  push:
    branches: [main, ci-cd]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./app
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        os: ['ubuntu-latest']
    steps:
      - name: Check out app code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up database and Load data
        run: |
          python manage.py makemigrations
          python manage.py migrate
          python manage.py loaddata ./aluraflix/fixtures/programas_iniciais.json

      - name: Run tests
        run: |
          python manage.py test

  build:
    needs: test
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  deploy:
    needs: build
    uses: ./.github/workflows/ecs.yml
    with:
      image: true

  