name: Build application

on:
  workflow_call:

jobs:
  docker:
    runs-on: 'ubuntu:latest'
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build ./app --file Dockerfile --tag aluraflix-api:$(date +%s) #sha


