on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  ecs:
    name: Deploy to Amazon ECS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Download task definition
      #   run: |
      #     aws ecs describe-task-definition --task-definition aluraflix --query taskDefinition > task-definition.json

      - run: ${{ inputs.config-path }}

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: aluraflix-api
          image: ${{ needs.docker.outputs.image }}
          # image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: service-aluraflix
          cluster: aluraflix-cluster
          wait-for-service-stability: true
